In [30]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

dataset = pd.read_csv(r'C:\Users\Kritika Goyal\Desktop\cocatinatefilenew.csv') 
  
# Import dataset 
df = pd.read_csv(r'C:\Users\Kritika Goyal\Desktop\cocatinatefilenew.csv') 
  
df['labels'].unique() 

# Import label encoder 
from sklearn import preprocessing 
  
# label_encoder object knows how to understand word labels. 
label_encoder = preprocessing.LabelEncoder() 
  
# Encode labels in column 'species'. 
df['labels']= label_encoder.fit_transform(df['labels']) 
  
df['labels'].unique() 
df.drop(df.columns[df.columns.str.contains('unnamed',case = False)],axis = 1, inplace = True)
#dataset1 = pd.read_csv('L_2048_T1_40.csv')
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 40)

# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
print(X_train.shape)
print(X_test.shape)



(312, 41)
(78, 41)


In [28]:
from sklearn import svm
from sklearn import metrics

clf = svm.SVC(kernel='linear',gamma='auto',C=1000,max_iter=1000)
clf.fit(X_train, y_train)
y_pred1= clf.predict(X_train)
#y_pred2 = clf.predict(X_val)
y_pred = clf.predict(X_test)

print("SVM model accuracy on training set:", metrics.accuracy_score(y_train, y_pred1))
#print("SVM model accuracy on validation set:", metrics.accuracy_score(y_val, y_pred2))
print("SVM model accuracy on test set:", metrics.accuracy_score(y_test, y_pred))
print(metrics.classification_report(y_test, y_pred))
print(metrics.confusion_matrix(y_test, y_pred))



C:\Users\Kritika Goyal\Anaconda3\lib\site-packages\sklearn\svm\base.py:244: ConvergenceWarning: Solver terminated early (max_iter=1000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)


SVM model accuracy on training set: 1.0
SVM model accuracy on test set: 0.8205128205128205
              precision    recall  f1-score   support

           0       0.81      0.88      0.85        25
           1       0.62      0.45      0.53        11
           2       0.67      0.71      0.69        14
           3       0.94      0.94      0.94        17
           4       1.00      1.00      1.00        11

   micro avg       0.82      0.82      0.82        78
   macro avg       0.81      0.80      0.80        78
weighted avg       0.82      0.82      0.82        78

[[22  1  2  0  0]
 [ 2  5  3  1  0]
 [ 3  1 10  0  0]
 [ 0  1  0 16  0]
 [ 0  0  0  0 11]]
