In [1]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

dataset = pd.read_csv(r'E:\Acoustic\Dataset\Experiment2withalframes\exp2cocatinatefilenew.csv') 
  
# Import dataset 
df = pd.read_csv(r'E:\Acoustic\Dataset\Experiment2withalframes\exp2cocatinatefilenew.csv') 
  
df['labels'].unique() 

# Import label encoder 
from sklearn import preprocessing 
  
# label_encoder object knows how to understand word labels. 
label_encoder = preprocessing.LabelEncoder() 
  
# Encode labels in column 'species'. 
df['labels']= label_encoder.fit_transform(df['labels']) 
  
df['labels'].unique() 
df.drop(df.columns[df.columns.str.contains('unnamed',case = False)],axis = 1, inplace = True)
#dataset1 = pd.read_csv('L_2048_T1_40.csv')
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 40)

# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
print(X_train.shape)
print(X_test.shape)



(21232, 41)
(5309, 41)


In [2]:
from sklearn import svm
from sklearn import metrics

clf = svm.SVC(kernel='linear',gamma='auto',C=1000,max_iter=1000)
clf.fit(X_train, y_train)
y_pred1= clf.predict(X_train)
#y_pred2 = clf.predict(X_val)
y_pred = clf.predict(X_test)

print("SVM model accuracy on training set:", metrics.accuracy_score(y_train, y_pred1))
#print("SVM model accuracy on validation set:", metrics.accuracy_score(y_val, y_pred2))
print("SVM model accuracy on test set:", metrics.accuracy_score(y_test, y_pred))
print(metrics.classification_report(y_test, y_pred))
print(metrics.confusion_matrix(y_test, y_pred))

C:\Users\Kritika Goyal\Anaconda3\lib\site-packages\sklearn\svm\base.py:244: ConvergenceWarning: Solver terminated early (max_iter=1000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)


SVM model accuracy on training set: 0.3286077618688772
SVM model accuracy on test set: 0.3328310416274251
              precision    recall  f1-score   support

           0       0.48      0.38      0.42      1376
           1       0.16      0.16      0.16       661
           2       0.18      0.15      0.16       668
           3       0.23      0.23      0.23       706
           4       0.28      0.46      0.35       808
           5       0.51      0.47      0.49      1090

   micro avg       0.33      0.33      0.33      5309
   macro avg       0.31      0.31      0.30      5309
weighted avg       0.35      0.33      0.33      5309

[[516 227 213 247 138  35]
 [135 109  57 124 137  99]
 [122  89 100  91 166 100]
 [188 105 109 159  91  54]
 [ 69  76  49  47 373 194]
 [ 40  93  20  18 409 510]]
